### ISSUE TITLE
output is black

### ISSUE THREAD

**Issue by Blokheck011** [supermosh/supermosh.github.io#1]
so i created a video using supermosh, but when i click render, it will prepare the segments just fine, but when it runs them its entirely black without sound, is there a solution for this?

**Comment by Blokheck011** [comment]
browsers: opera gx and chromium (NOT CHROME).
codec and dimensions: i tried multiple videos, all mp4, each one had different length and dimensions.
see this video for reference, info follows: https://user-images.githubusercontent.com/105729942/168971257-90932a50-423e-41a7-99d0-1ae2ed3d59c3.mp4 codec from output:
 Video
308x480
1s < this is wrong, according to all segments it should be 4s long, original vid is 7s long.
16Kb
type: video/x-matroska;codecs=avc1

**Comment by Blokheck011** [comment]
just saw, my first few tries actually worked, but all other attempts to make a vid after that failed.

**Comment by ninofiliu** [comment]
I can't reproduce the issue sorry!

**Comment by Ethanjoyce2010** [comment]
> browsers: opera gx and chromium (NOT CHROME). codec and dimensions: i tried multiple videos, all mp4, each one had different length and dimensions. see this video for reference, info follows: https://user-images.githubusercontent.com/105729942/168971257-90932a50-423e-41a7-99d0-1ae2ed3d59c3.mp4 codec from output: Video 308x480 1s < this is wrong, according to all segments it should be 4s long, original vid is 7s long. 16Kb type: video/x-matroska;codecs=avc1

After a million years, i can say opera gx DOES NOT work with supermosh.

**Comment by ninofiliu** [comment]
yeah sure well i'm not supporting anything besides Firefox and Chrome, but glad you brought this up:)

**Comment by Ethanjoyce2010** [comment]
> yeah sure well i'm not supporting anything besides Firefox and Chrome, but glad you brought this up:)

After a bit of testing I can say, th does not work on ogx at all and is kinda broken on brave.
