### ISSUE TITLE
Video doesn't save as proper video file

### ISSUE THREAD

**Issue by fernanlg** [supermosh/supermosh.github.io#10]
Hello, 

I'm using Supermosh for the first time and my issue is that the video saves as a text file. Thanks for Supermosh and all your work!

Sincerely, 
Fern

**Comment by ninofiliu** [comment]
Hello! Saving files is done natively by the browser so I don't have control over that, but you should be able to add an .mp4 or .webm extension to your text file and it should work. It's not really text files, it's a video file, just without the proper extensions so some OSes struggle with that. Tell me if that helps.

**Comment by ninofiliu** [comment]
Stale, closing
