### ISSUE TITLE
Stopping

### ISSUE THREAD

**Issue by Loganh357** [supermosh/supermosh.github.io#11]
The process randomly stops.

| Clip length | works | problem |
| ------------------|------------|--------------|
| 10+ | No. | Randomly stops |
| >10 | Probably | It probably works at under 10 seconds |

**Comment by ninofiliu** [comment]
Thanks for opening up an issue but unfortunately I have no idea what you are talking about

**Comment by ninofiliu** [comment]
Okay but can you provide more informations?

- OS
- Video you're using
- how much RAM and VRAM you have
- Is there errors logged in the console
- Can I have a screencast

Etc etc etc

Basically put yourself in my shoes - I genuinely want to solve my software's issues but it's very difficult now to reproduce your issue, as such I won't be able to fix it until you provide me with the necessary informations and assets for me to reproduce it

**Comment by ninofiliu** [comment]
Okay, I don't have a Kindle at home to reproduce the bug, and I only target support for ubuntu/macos/windows on firefox/chromium-based, and without error logs or screencasts I can't do anything, so closing this
