### ISSUE TITLE
Page does not work. I can't insert an video.

### ISSUE THREAD

**Issue by DONTDDOSME** [supermosh/supermosh.github.io#4]
I'll show you why.
****here****
![Screenshot 2023-08-09 234821](https://github.com/supermosh/supermosh.github.io/assets/135388372/1abc180d-cfdb-4537-9f4e-84de51ce9d83)
UPDATE: The page is just white. please fix this. it's unusable and it's only white.

**Comment by ninofiliu** [comment]
do you see any errors in the console? what browser are you using? can you upload the video you're trying it with?

**Comment by DONTDDOSME** [comment]
i see 8 errors and i don't have storage. and i use chrome.

**Comment by DONTDDOSME** [comment]
also. i only see white in the website as the update said

**Comment by ninofiliu** [comment]
can you copy-paste the error texte? and can you upload the video *here* so I can try out uploading it *on my website* and see what's wrong? Or does it do that with every video?

**Comment by DONTDDOSME** [comment]
> can you copy-paste the error texte? and can you upload the video _here_ so I can try out uploading it _on my website_ and see what's wrong? Or does it do that with every video?

it's fixed. just fix the black video output and make support for .asf and .avi files they're also videos!

**Comment by ninofiliu** [comment]
I'm not the one controlling support for .asf and .avi, I rely on the browser internal capabilities. Glad your issue is resolved tho :)
