### ISSUE TITLE
Crash if delete video during rendering

### ISSUE THREAD

**Issue by SurvivingCuriosity** [supermosh/supermosh.github.io#7]
Program crashes either when
-You delete a video while rendering
-You delete a segment while rendering

TypeError: Cannot read properties of undefined (reading 'transform')

**Comment by ninofiliu** [comment]
yeah well i'm not sure you're supposed to do that but thanks for bringing it up xx

**Comment by SurvivingCuriosity** [comment]
hehehe ye i know u are not suposed to do that... just for the program to be more robust... i used to be sw tester for a short period of time so i just like to break things XD

**Comment by ninofiliu** [comment]
noted! i added this to the roadmap of "nice to have"s i'll implement once i'll get time to get back on the project:)
