### ISSUE TITLE
Can you add a feature to up/down scale videos so that they can be rendered together?

### ISSUE THREAD

**Issue by numbah12345** [supermosh/supermosh.github.io#9]
Just tried to use it, and it would not let me render because the videos I chose were of two different resolutions. I can easily rescale them and do it, but if possible, itd be nice to not have to. thx

**Comment by ninofiliu** [comment]
Hello! I won't add that, resizing videos can be done by users with the software of their choice. Namely it can be done in [one line using ffmpeg](http://trac.ffmpeg.org/wiki/Scaling)

```sh
ffmpeg -i my-4K-video.mp4 -vf scale=1920:1080 my-HD-video.mp4
```
